### PR TITLE
Provide Event Description as a standard column

### PR DESCRIPTION
**Pull request by loldenburg**
just like for dimensions, calc Metrics and segments. Eg the description of "event89".

### CODE REVIEW

**Comment by pitchmuc** [comment]
Hello @loldenburg 
I had it before but for some reportSuite were broken in my tests and it is not always there. 
You can still request it by adding the description parameter on the method getDimensions and getMetrics.

**Comment by loldenburg** [comment]
Thx! Strange, why would the event description not be there in a RS? 
The description column is even supported in the official "swagger".
What do you mean by "by adding the description parameter on the method getDimensions and getMetrics".

**Comment by pitchmuc** [comment]
Yeah, I found that strange as well. I need to investigate why, but to be safe, I prefered to make it optional. 
It is also not critical when comparing reportSuite setup. 

I just saw that I didn't include an option for it, just for DataGroup.
I will patch the release and add it the same way than for dimensions, as a parameter. 
`getDimensions(self, rsid: str, tags: bool = False, description:bool=False, save=False, **kwargs)`

I hope that will be alright

**Comment by pitchmuc** [comment]
Let me know if time critical. Not big effort but not my focus right now.

**Comment by loldenburg** [comment]
thx, not time-critical! In the next 2-3 weeks would be great. I can help myself with a custom fork in the worst case

**Comment by pitchmuc** [comment]
It should be fixed in the last commit.
Could you test the last commit 2f76cb1 ?
`pip install git+https://github.com/pitchmuc/adobe-analytics-api-2.0.git@2f76cb129b3e0582988a9ce9ae6b22124f9cc76f`

**Comment by loldenburg** [comment]
hmm in my case the request now never comes back and I have to abort Python manually. But I will restart and try again.

**Comment by loldenburg** [comment]
ok Restart helped. Was probably some caching issue. Thanks, works!!

**Comment by pitchmuc** [comment]
Very welcome.
Sorry I miss that still.

**Pull request closed without merging**
